let bookTitle: string = "TypeScript Basics";
const libraryName: string = "My Library";
let numberOfBooks: number = 10;
let isLibraryOpen: boolean = true;

let titulo: string;
let autor: string;
let genero: string;
let idioma: string;
let precio: number;
let formato: string;
let isbn: string;
let descripcion: string;
let estado: string;
let ubicacion: string;
let fecha_publicacion: Date;
let editorial: string;
let paginas: number;
let dimensiones: string;
let peso: number;
let disponible: boolean;

titulo = "Cien años de soledad";
autor = "Gabriel García Márquez";
genero = "Ficción";
idioma = "Español";
precio = 20.99;
formato = "Tapa blanda";
isbn = "978-0307474728";
descripcion = "Una obra maestra de la literatura latinoamericana que narra la historia de la familia Buendía en el ficticio pueblo de Macondo.";
estado = "Nuevo";
ubicacion = "Sección de ficción";
fecha_publicacion = new Date(1967, 4, 30);
editorial = "Editorial Sudamericana";
paginas = 432;
dimensiones = "13.5 x 2.7 x 20.3 cm";
peso = 363;
disponible = true;